[agent]
  interval = "1s"
  flush_interval = "1s"
  omit_hostname = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["audio/fake"]
  username = "telegraf"
  password = "${MQTT_TELEGRAF_PASS}"
  data_format = "influx"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["homeassistant/sensor/+/state"]
  username = "telegraf"
  password = "${MQTT_TELEGRAF_PASS}"
  data_format = "value"
  data_type = "float"
  name_override = "audio"
  [inputs.mqtt_consumer.tags]
    source = "h2"

[[processors.rename]]
  namepass = ["audio"]
  [[processors.rename.replace]]
    field = "value"
    dest = "rms"

[[outputs.http]]
  url = "http://influx:8181/api/v3/write_lp?db=iot"
  method = "POST"
  data_format = "influx"
  [outputs.http.headers]
    Authorization = "Bearer ${INFLUX_TOKEN}"
